---
# tasks file for prod
- name: Ensure apps for are installed
  apt: name={{ item }} state=present
  with_items:
    - tomcat9

- name: sync war
  synchronize:
    mode: push
    src: '{{ src_path }}'
    dest: '{{ dest_path }}'
  delegate_to: 178.154.192.98