---
# tasks file for prod
- name: Ensure apps for are installed
  apt: name={{ item }} state=present
  with_items:
      - tomcat9

- name: Copy war
  copy: src=/tmp/hello-1.0.war dest={{ dest_path }}